version: '3.8'

networks:
  evisa:

services:

  app:
    container_name: app
    build:
      context: ./docker
    environment:
      - APP_ENV=prod
      - DATABASE_URL=postgresql://root:QT6e5APtSYaU@db:localhost:5432/evisa_db?serverVersion=14
      - REMOTE_HOST=host.docker.internal
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/html
    networks:
      - evisa

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 90:80
    depends_on:
      - app
    networks:
      - evisa
